#!/usr/bin/env bash

# Settings

typeset -r monitors=(
	"I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X"
)
bspc monitor -d ${monitors[@]}
bspc config focused_border_color "#cc2623"
bspc config normal_border_color "#332720"
bspc config presel_feedback_color "#b35f6c"
bspc config focus_follows_pointer true
bspc config border_width 3
bspc config window_gap 8

# Startup

sxhkd &
~/.fehbg &

