#!/usr/bin/env bash

# Defines the quantity of workspaces available.
# Each one of them will be accessed by a number key.
bspc monitor -d I II III IV V VI VII VIII IX X
# Defines the theme and style used in the windows.
bspc config focused_border_color  "#cc2623"
bspc config normal_border_color   "#332720"
bspc config presel_feedback_color "#b35f6c"
bspc config border_width          3
bspc config window_gap            8
# Makes the focused window be changed when moving the cursor over it.
bspc config focus_follows_pointer true

# Defines the programs executed in the startup of the window manager.
sxhkd    & # The program that sets keymaps.
polybar  & # The bar.
picom    & # The windows compositor.
~/.fehbg & # The wallpaper.
