#!/usr/bin/env bash

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config focused_border_color "#b32815"
bspc config normal_border_color "#140f0f"
bspc config presel_feedback_color "#899980"
bspc config border_width 3
bspc config window_gap 8
bspc config focus_follows_pointer true
sxhkd &
picom &
~/.fehbg &
